### PR TITLE
updated to 1.2.4

### PR DESCRIPTION
**Pull request by nirajd**

### CODE REVIEW

**Comment by nirajd** [comment]
- [x] Hmm... SRC_DIR gets deleted before test and no doc on how to run nosetests

- [ ] File "C:\Miniconda\lib\site-packages\conda_build\conda_interface.py", line 266, in <module> get_local_urls = cc.get_local_urls NameError: name 'cc' is not defined
    - [ ] conda forced to 4.1.12, which probably should work, but obvious-ci requires it to be upgraded, which breaks 2.7 and 3.5

**Comment by nirajd** [comment]
cc.get_local_urls -- cc not defined in conda-build.

**Comment by bollwyvl** [comment]
@nirajd, thanks for the PR, sorry for the delay in review!

So `SRC_DIR` begat [`source_files`](https://conda.io/docs/building/meta-yaml.html#source-files) and still trips me up.

As for the conda internal error, boo! I'll give it a whack with `conda-smithy rerender`, and we'll see if that doesn't patch it up on another PR. I'll add you as a maintainer, too!

**Comment by bollwyvl** [comment]
Ooh, looking at the upstream, it appears the tests are shipped with the package now, hooray! That will just become `nosetests category_encoders.tests`, instead of all the `SRC`/`source` nonsense...

**Pull request closed without merging**
